[0m12:47:03.165480 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f09efcac880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f09eec63df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f09eec63e80>]}


============================== 12:47:03.168358 | efe7d58d-c3f7-42ff-8274-8ee529da77dd ==============================
[0m12:47:03.168358 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:47:03.168816 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/janne/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:47:03.179364 [info ] [MainThread]: dbt version: 1.9.3
[0m12:47:03.179715 [info ] [MainThread]: python version: 3.10.12
[0m12:47:03.179981 [info ] [MainThread]: python path: /home/janne/nerd-facts-dbt/venv/bin/python3
[0m12:47:03.180229 [info ] [MainThread]: os info: Linux-5.15.0-134-generic-x86_64-with-glibc2.35
[0m12:47:03.235906 [info ] [MainThread]: Using profiles dir at /home/janne/.dbt
[0m12:47:03.236313 [info ] [MainThread]: Using profiles.yml file at /home/janne/.dbt/profiles.yml
[0m12:47:03.236629 [info ] [MainThread]: Using dbt_project.yml file at /home/janne/nerd-facts-dbt/dbt_project.yml
[0m12:47:03.237249 [info ] [MainThread]: adapter type: postgres
[0m12:47:03.237553 [info ] [MainThread]: adapter version: 1.9.0
[0m12:47:03.237847 [info ] [MainThread]: Configuration:
[0m12:47:03.238098 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m12:47:03.238335 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m12:47:03.238555 [info ] [MainThread]: Required dependencies:
[0m12:47:03.238816 [debug] [MainThread]: Executing "git --help"
[0m12:47:03.240660 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m12:47:03.240989 [debug] [MainThread]: STDERR: "b''"
[0m12:47:03.241210 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m12:47:03.241550 [info ] [MainThread]: Connection:
[0m12:47:03.241811 [info ] [MainThread]:   host: localhost
[0m12:47:03.242044 [info ] [MainThread]:   port: 5432
[0m12:47:03.242275 [info ] [MainThread]:   user: dbt_user
[0m12:47:03.242494 [info ] [MainThread]:   database: nerd_facts
[0m12:47:03.242733 [info ] [MainThread]:   schema: public
[0m12:47:03.242976 [info ] [MainThread]:   connect_timeout: 10
[0m12:47:03.243193 [info ] [MainThread]:   role: None
[0m12:47:03.243409 [info ] [MainThread]:   search_path: None
[0m12:47:03.243635 [info ] [MainThread]:   keepalives_idle: 0
[0m12:47:03.243871 [info ] [MainThread]:   sslmode: None
[0m12:47:03.244110 [info ] [MainThread]:   sslcert: None
[0m12:47:03.244344 [info ] [MainThread]:   sslkey: None
[0m12:47:03.244560 [info ] [MainThread]:   sslrootcert: None
[0m12:47:03.244799 [info ] [MainThread]:   application_name: dbt
[0m12:47:03.245016 [info ] [MainThread]:   retries: 1
[0m12:47:03.245393 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m12:47:03.314935 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m12:47:03.342859 [debug] [MainThread]: Using postgres connection "debug"
[0m12:47:03.343246 [debug] [MainThread]: On debug: select 1 as id
[0m12:47:03.343487 [debug] [MainThread]: Opening a new connection, currently in state init
[0m12:47:03.357978 [debug] [MainThread]: SQL status: SELECT 1 in 0.014 seconds
[0m12:47:03.358835 [debug] [MainThread]: On debug: Close
[0m12:47:03.359258 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m12:47:03.359673 [info ] [MainThread]: [31m1 check failed:[0m
[0m12:47:03.359996 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/janne/nerd-facts-dbt/dbt_project.yml> not found

[0m12:47:03.361263 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.24673879, "process_in_blocks": "70232", "process_kernel_time": 0.138722, "process_mem_max_rss": "99044", "process_out_blocks": "24", "process_user_time": 1.105472}
[0m12:47:03.361675 [debug] [MainThread]: Command `dbt debug` failed at 12:47:03.361587 after 0.25 seconds
[0m12:47:03.361938 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m12:47:03.362197 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f09efcac880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f09eec63f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f09ee375ab0>]}
[0m12:47:03.362488 [debug] [MainThread]: Flushing usage events
[0m12:47:03.757987 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:36:39.530865 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8262d688b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8263e5a320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8263e5a380>]}


============================== 11:36:39.533045 | 9f1ea0d4-634f-4e1e-aec9-9e5a7db09ec5 ==============================
[0m11:36:39.533045 [info ] [MainThread]: Running with dbt=1.9.2
[0m11:36:39.533496 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/janne/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select models/marts/pokemon/fact_pokemon.sql models/marts/pokemon/fact_pokemon_stats.sql models/marts/star_wars/fact_sw_characters.sql models/marts/netrunner/fact_netrunner_card_power.sql', 'send_anonymous_usage_stats': 'True'}
[0m11:36:39.533870 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:36:39.534560 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.0597988, "process_in_blocks": "24", "process_kernel_time": 0.064194, "process_mem_max_rss": "85000", "process_out_blocks": "16", "process_user_time": 0.918838}
[0m11:36:39.535017 [debug] [MainThread]: Command `dbt run` failed at 11:36:39.534932 after 0.06 seconds
[0m11:36:39.535310 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8262d688b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8263e5a2f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8263e5a320>]}
[0m11:36:39.535627 [debug] [MainThread]: Flushing usage events
[0m11:36:40.035797 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:18:11.154201 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f598b19cc70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f598b0671f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f598a2fd480>]}


============================== 12:18:11.156710 | 59e51663-580b-49fb-977f-7865b38c8cbb ==============================
[0m12:18:11.156710 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:18:11.157293 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/janne/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --select dim_pokemon_moves', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:18:11.157744 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:18:11.158524 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.050036542, "process_in_blocks": "0", "process_kernel_time": 0.104012, "process_mem_max_rss": "85076", "process_out_blocks": "8", "process_user_time": 0.887816}
[0m12:18:11.159051 [debug] [MainThread]: Command `dbt run` failed at 12:18:11.158953 after 0.05 seconds
[0m12:18:11.159410 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f598b19cc70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f598a2fd810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f598a2fd450>]}
[0m12:18:11.159800 [debug] [MainThread]: Flushing usage events
[0m12:18:11.579484 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:23:44.296960 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f46e49dcbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f46e59ce8c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f46e59ccdf0>]}


============================== 12:23:44.299815 | ae57e45d-dcdb-474b-a79c-5d69ab0bc6e3 ==============================
[0m12:23:44.299815 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:23:44.300528 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/janne/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select bridge_pokemon_abilities', 'send_anonymous_usage_stats': 'True'}
[0m12:23:44.301096 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:23:44.301946 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.049034946, "process_in_blocks": "0", "process_kernel_time": 0.079964, "process_mem_max_rss": "85004", "process_out_blocks": "8", "process_user_time": 0.936713}
[0m12:23:44.302497 [debug] [MainThread]: Command `dbt run` failed at 12:23:44.302390 after 0.05 seconds
[0m12:23:44.302874 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f46e49dcbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f46e59cdf30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f46e59cd510>]}
[0m12:23:44.303262 [debug] [MainThread]: Flushing usage events
[0m12:23:44.743349 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:25:36.987510 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c2adfcc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c2bdf7af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c2bdf5f90>]}


============================== 12:25:36.989717 | a3bdaea4-fd4b-4f7d-af30-bda92cf4b117 ==============================
[0m12:25:36.989717 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:25:36.990165 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/janne/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run --select bridge_pokemon_abilities', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:25:36.990544 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:25:36.991223 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.047683533, "process_in_blocks": "0", "process_kernel_time": 0.047987, "process_mem_max_rss": "84900", "process_out_blocks": "16", "process_user_time": 0.939383}
[0m12:25:36.991680 [debug] [MainThread]: Command `dbt run` failed at 12:25:36.991591 after 0.05 seconds
[0m12:25:36.991970 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c2adfcc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c2bdf7af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c2bdf6920>]}
[0m12:25:36.992268 [debug] [MainThread]: Flushing usage events
[0m12:25:37.438495 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:30:13.768418 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f74b7800c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f74b78bbcd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f74b87f9de0>]}


============================== 12:30:13.770591 | 279212a4-d26b-4c50-be3a-13853b0157eb ==============================
[0m12:30:13.770591 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:30:13.771032 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/janne/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --select bridge_pokemon_abilities', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:30:13.771436 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:30:13.772133 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.049751885, "process_in_blocks": "0", "process_kernel_time": 0.044074, "process_mem_max_rss": "84984", "process_out_blocks": "8", "process_user_time": 0.961322}
[0m12:30:13.772592 [debug] [MainThread]: Command `dbt run` failed at 12:30:13.772504 after 0.05 seconds
[0m12:30:13.772890 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f74b7800c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f74b87f9de0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f74b87f8b50>]}
[0m12:30:13.773205 [debug] [MainThread]: Flushing usage events
[0m12:30:14.212674 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:31:18.705963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f451b4d4ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f451b39dae0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f451a6393c0>]}


============================== 12:31:18.708138 | 85f64d74-daed-4042-8f85-e58a8ec59563 ==============================
[0m12:31:18.708138 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:31:18.708586 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/janne/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt compile --select bridge_pokemon_abilities bridge_pokemon_moves', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:31:18.708971 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:31:18.709689 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_success": false, "command_wall_clock_time": 0.05116161, "process_in_blocks": "0", "process_kernel_time": 0.095822, "process_mem_max_rss": "85136", "process_out_blocks": "8", "process_user_time": 0.870465}
[0m12:31:18.710130 [debug] [MainThread]: Command `dbt compile` failed at 12:31:18.710052 after 0.05 seconds
[0m12:31:18.710419 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f451b4d4ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f451a639810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f451a6386a0>]}
[0m12:31:18.710722 [debug] [MainThread]: Flushing usage events
[0m12:31:19.150365 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:34:47.797841 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f204d910c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f204d9d7cd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f204e9d9de0>]}


============================== 12:34:47.800012 | 1fa651ff-cad3-4824-955f-dddb2202d8ed ==============================
[0m12:34:47.800012 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:34:47.800453 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/janne/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run --select bridge_pokemon_abilities', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:34:47.800833 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:34:47.801537 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.051670898, "process_in_blocks": "0", "process_kernel_time": 0.055987, "process_mem_max_rss": "85080", "process_out_blocks": "16", "process_user_time": 0.967893}
[0m12:34:47.802000 [debug] [MainThread]: Command `dbt run` failed at 12:34:47.801911 after 0.05 seconds
[0m12:34:47.802303 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f204d910c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f204e9d9de0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f204e9d8b50>]}
[0m12:34:47.802606 [debug] [MainThread]: Flushing usage events
[0m12:34:48.242799 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:52:54.544541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd45acf0c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd459e52350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd459e51510>]}


============================== 12:52:54.546731 | 6eda5960-be10-4138-8ec8-495876b88ca6 ==============================
[0m12:52:54.546731 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:52:54.547161 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/janne/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --select dim_characters fact_power_ratings fact_sw_characters int_swapi_characters_species dim_locations fact_starships', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:52:54.547537 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:52:54.548264 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.047665484, "process_in_blocks": "0", "process_kernel_time": 0.06815, "process_mem_max_rss": "84748", "process_out_blocks": "8", "process_user_time": 0.909749}
[0m12:52:54.548722 [debug] [MainThread]: Command `dbt run` failed at 12:52:54.548635 after 0.05 seconds
[0m12:52:54.549031 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd45acf0c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd45a237580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd459e51330>]}
[0m12:52:54.549341 [debug] [MainThread]: Flushing usage events
[0m12:52:54.970323 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:21:24.511500 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff9592e0b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff95a28f160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff95a28ee00>]}


============================== 13:21:24.513726 | 2c3659d7-e3ac-4a32-95f7-399f544e27be ==============================
[0m13:21:24.513726 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:21:24.514172 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/janne/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --select fact_starships', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:21:24.514544 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:21:24.515203 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.048354775, "process_in_blocks": "0", "process_kernel_time": 0.060075, "process_mem_max_rss": "84932", "process_out_blocks": "16", "process_user_time": 0.916827}
[0m13:21:24.515660 [debug] [MainThread]: Command `dbt run` failed at 13:21:24.515556 after 0.05 seconds
[0m13:21:24.515952 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff9592e0b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff95a28f220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff95a28f160>]}
[0m13:21:24.516249 [debug] [MainThread]: Flushing usage events
[0m13:21:24.954399 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:56:24.270507 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bef290c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bf03118a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bf0310160>]}


============================== 12:56:24.274189 | 0e062972-0d59-4bd4-b91b-6dc24c53a368 ==============================
[0m12:56:24.274189 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:56:24.275005 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/janne/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt ls', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:56:24.275915 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:56:24.277036 [debug] [MainThread]: Resource report: {"command_name": "list", "command_success": false, "command_wall_clock_time": 0.059804115, "process_in_blocks": "0", "process_kernel_time": 0.052018, "process_mem_max_rss": "85216", "process_out_blocks": "8", "process_user_time": 0.968114}
[0m12:56:24.277829 [debug] [MainThread]: Command `dbt ls` failed at 12:56:24.277697 after 0.06 seconds
[0m12:56:24.278363 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bef290c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bf0310d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bf03118a0>]}
[0m12:56:24.278913 [debug] [MainThread]: Flushing usage events
[0m12:56:24.703145 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:57:27.319238 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcbadee0c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcbad03faf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcbad03df90>]}


============================== 12:57:27.321994 | 29b81570-6d4b-4c32-a827-0f2a13da09ca ==============================
[0m12:57:27.321994 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:57:27.322629 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/janne/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select marts.obt.*', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:57:27.323158 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/janne/nerd-facts-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:57:27.324048 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.050411314, "process_in_blocks": "0", "process_kernel_time": 0.059793, "process_mem_max_rss": "84744", "process_out_blocks": "8", "process_user_time": 0.943891}
[0m12:57:27.324594 [debug] [MainThread]: Command `dbt run` failed at 12:57:27.324490 after 0.05 seconds
[0m12:57:27.324954 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcbadee0c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcbad03faf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcbad03e920>]}
[0m12:57:27.325357 [debug] [MainThread]: Flushing usage events
[0m12:57:27.754120 [debug] [MainThread]: An error was encountered while trying to flush usage events
